version: '3.8'

services:
  app:
    build:
      context: ./q_learning
      dockerfile: Dockerfile
    container_name: q_learning_app
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    volumes:
      - ./q_learning:/app
    environment:
      - PYTHONUNBUFFERED=1
